### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by xin2017338** [suxin2017/rust-less#1]
It's a bit much, but fear not
<details open>
  <summary>variables</summary>

- [x] variables defined & nest variables defined
https://github.com/suxin2017/rust-less/pull/2
- [ ] selectors varible express
- [ ] string variable express
- [x] variable express
https://github.com/suxin2017/rust-less/pull/3
- [ ] properties variable express
- [ ] variable variables
- [ ] properties as variables
</details>

- [x] opertations
https://github.com/suxin2017/rust-less/pull/3

<details>
    <summary>mixins</summary>

- [ ] Mixins With Parentheses
- [ ] Selectors in Mixins
- [ ] Namespaces
- [ ] Guarded Namespaces
- [ ] The <code>!important</code> keyword
- [ ] Parametric Mixins
- [ ] Pattern-matching
- [ ] Using Mixins as Functions
- [ ] Recursive Mixins
- [ ] Mixin Guards
- [ ] Aliasing Mixins
</details>

<details>
    <summary>Parent Selectors</summary>

- [x] nesting
https://github.com/suxin2017/rust-less/pull/4
- [ ] nest at-rules adn bubbling
</details>

<details>
   <summary>more</summary>

- [ ] operations
- [ ] calce exception
- [ ] escaping
- [ ] namespaces and accessors
- [ ] maps
- [ ] scope
- [x] comments
- [ ] import
- [ ] functions
- [ ] if
- [ ] boolean
- [ ] string
   - [ ] escape
   - [ ] e
   - [ ] %
   - [ ] replace
   - [ ] list
   - [ ] extract
   - [ ] range
   - [ ] each
   - [ ] match
   - [ ] ceil
   - [ ] floor
   - [ ] percentage
   - [ ] round
   - [ ] sqrt
   - [ ] abs
   - [ ] sin
   - [ ] asin
   - [ ] cos
   - [ ] acos
   - [ ] tan
   - [ ] atan
   - [ ] pi
   - [ ] pow
   - [ ] mod
   - [ ] min
   - [ ] max
   - [ ] isnumber
   - [ ] isstring
   - [ ] iscolor
   - [ ] iskeyword
   - [ ] isurl
   - [ ] ispixel
   - [ ] isem
   - [ ] ispercentage
   - [ ] isunit
   - [ ] isurleset
   - [ ] isdefined
   - [ ] color
   - [ ] image-size
   - [ ] image-width
   - [ ] image-height
   - [ ] covert
   - [ ] data-uri
   - [ ] default
   - [ ] unit
   - [ ] get-unit
   - [ ] svg-gradient
   - [ ] rgb
   - [ ] rgba
   - [ ] argb
   - [ ] hsl
   - [ ] hsla
   - [ ] hsv
   - [ ] hsva
   - [ ] hue
   - [ ] staturation
   - [ ] lightness
   - [ ] hsvhue
   - [ ] hsvsaturation
   - [ ] hsvvalue
   - [ ] red
   - [ ] green
   - [ ] blue
   - [ ] alpha
   - [ ] luma
   - [ ] luminance
   - [ ] sqturate
   - [ ] desaturate
   - [ ] lighten
   - [ ] darken
   - [ ] fadein
   - [ ] fadeout
   - [ ] fade
   - [ ] spin
   - [ ] mix
   - [ ] tint
   - [ ] shade
   - [ ] geryscale
   - [ ] contrast
   - [ ] multiply
   - [ ] screen
   - [ ] overlay
   - [ ] softlight
   - [ ] hardlight
   - [ ] difference
   - [ ] exclusion
   - [ ] average
   - [ ] negation 
</details>
